# Generated by Django 4.2 on 2023-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choises',
            new_name='Choice',
        ),
    ]
